
import { Pet } from "../models/pet.model.js";
import { User } from "../models/user.model.js";

export async function petSeeds() {
  const guardians = await User.findAll({ where: { role: "guardian" } });

  if (guardians.length === 0) {
    console.log("Nenhum guardião encontrado. Execute a seed de usuários primeiro.");
    return;
  }

  const pets = [
    {
      tipo: "gato",
      nome: "Hermione",
      idade: "2 anos",
      imagem: "../uploads/hermione-gata.jpg",
      descricao: "Gatinha brincalhona e curiosa.",
      observacoes: "Adora subir em móveis.",
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Anakin",
      idade: "1 ano",
      imagem: "../uploads/anakin-gato.jpg",
      descricao: "Gato esperto e carinhoso.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "macho",
      vacinado: "não",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "cachorro",
      nome: "Marley",
      idade: "3 meses",
      imagem: "../uploads/marley-cachorro.jpg",
      descricao: "Cachorro esperto e leal.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "macho",
      vacinado: "sim",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "cachorro",
      nome: "Missy",
      idade: "2 anos",
      imagem: "../uploads/missy-cachorra.jpg",
      descricao: "Dócil e companheira.",
      observacoes: null,
      status: "Coração livre!",
      porte: "médio",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 3,
    },
    {
      tipo: "gato",
      nome: "Misty",
      idade: "3 anos",
      imagem: "../uploads/misty-gata.jpg",
      descricao: "Muito calma e companheira.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 4,
    },
    {
      tipo: "cachorro",
      nome: "Rex",
      idade: "3 anos",
      imagem: "../uploads/rex-cachorro.jpg",
      descricao: "Cão protetor e leal.",
      observacoes: "Ideal para quintal.",
      status: "Coração livre!",
      porte: "grande",
      sexo: "macho",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "cachorro",
      nome: "Lili",
      idade: "2 anos",
      imagem: "../uploads/lili-cachorra.jpg",
      descricao: "Muito ativa e inteligente.",
      observacoes: null,
      status: "Coração livre!",
      porte: "médio",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "cachorro",
      nome: "Dobby",
      idade: "1 ano",
      imagem: "../uploads/dobby-cachorro.jpg",
      descricao: "Cão alegre e sociável.",
      observacoes: null,
      status: "Coração livre!",
      porte: "grande",
      sexo: "macho",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "cachorro",
      nome: "Meg",
      idade: "6 anos",
      imagem: "../uploads/meg-cachorra.jpg",
      descricao: "Cachorra calma e obediente.",
      observacoes: null,
      status: "Coração livre!",
      porte: "grande",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "gato",
      nome: "Snow",
      idade: "2 anos",
      imagem: "../uploads/snow-gato.jpg",
      descricao: "Gato ativo e brincalhão.",
      observacoes: "Precisa de muito estímulo.",
      status: "Coração livre!",
      porte: "médio",
      sexo: "macho",
      vacinado: "sim",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Luna",
      idade: "4 meses",
      imagem: "../uploads/luna-gata.jpg",
      descricao: "Filhote doce e sociável.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Felix",
      idade: "6 meses",
      imagem: "../uploads/felix-cachorro.jpg",
      descricao: "Filhote elétrico e divertido.",
      observacoes: null,
      status: "Coração livre!",
      porte: "grande",
      sexo: "macho",
      vacinado: "não",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Wandinha",
      idade: "2 anos",
      imagem: "../uploads/wandinha-gata.jpg",
      descricao: "Gatinha tímida no começo, mas muito carinhosa.",
      observacoes: null,
      status: "Coração livren!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5
    },
    {
      tipo: "gato",
      nome: "Pitoco",
      idade: "1 ano",
      imagem: "../uploads/pitoco-gato.jpg",
      descricao: "Manso, dorminhoco e sociável.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "macho",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "gato",
      nome: "Nick",
      idade: "3 anos",
      imagem: "../uploads/nick-gato.jpg",
      descricao: "Tranquila e muito educada.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "não",
      castrado: "sim",
      guardianId: 3,
    },
    {
      tipo: "gato",
      nome: "Pichano",
      idade: "2 anos",
      imagem: "../uploads/pichano-gato.jpg",
      descricao: "Gato travesso e engraçado.",
      observacoes: "Ama brinquedos com penas.",
      status: "Coração livre!",
      porte: "médio",
      sexo: "macho",
      vacinado: "sim",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Jarvis",
      idade: "4 anos",
      imagem: "../uploads/jarvis-gato.jpg",
      descricao: "Gata adulta, tranquila e dócil.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "macho",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 3,
    },
    {
      tipo: "cachorro",
      nome: "Toby",
      idade: "8 meses",
      imagem: "../uploads/toby-cachorro.jpg",
      descricao: "Filhote ativo e brincalhão.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "macho",
      vacinado: "não",
      castrado: "não",
      guardianId: 2,
    },
    {
      tipo: "gato",
      nome: "Belota",
      idade: "3 anos",
      imagem: "../uploads/belota-gata.jpg",
      descricao: "Muito protetora e doce.",
      observacoes: null,
      status: "Coração livre!",
      porte: "médio",
      sexo: "fêmea",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "cachorro",
      nome: "Perseu",
      idade: "5 anos",
      imagem: "../uploads/perseu-cachorro.jpg",
      descricao: "Companheiro e fiel.",
      observacoes: null,
      status: "Coração livre!",
      porte: "grande",
      sexo: "macho",
      vacinado: "sim",
      castrado: "sim",
      guardianId: 5,
    },
    {
      tipo: "cachorro",
      nome: "Lola",
      idade: "1 ano",
      imagem: "../uploads/lola-cachorra.jpg",
      descricao: "Muito carinhosa e sociável.",
      observacoes: null,
      status: "Coração livre!",
      porte: "pequeno",
      sexo: "fêmea",
      vacinado: "não",
      castrado: "não",
      guardianId: 2,
    },
  ];

  for (const pet of pets) {
    const [obj, created] = await Pet.findOrCreate({
      where: { nome: pet.nome },
      defaults: pet,
    });

    if (created) {
      console.log(`Pet ${pet.nome} criado.`);
    } else {
      console.log(`Pet ${pet.nome} já existe.`);
    }
  }
}
